######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 12 03:38:14 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
