U = Intersection(S.Naturals, Interval(-oo, 10, right_open=True))
U = FiniteSet(*list(U))
display(Eq(Symbol('U'), U))
A = FiniteSet(2, 3, 5, 8)
B = FiniteSet(5, 6, 7)
C = FiniteSet(3, 5, 6, 9)
display(U - (A + B))
display((U - A) + (U - B))
display((U - A).intersect(B))
display(A.intersect(B).intersect(C))
display(A + B + C)
display(A.intersect(B).intersect(U - C))
