./" 「./"」で開始された行はコメントとして処理され、出力されません。
.TH EXAMPLE 7 "(last update)" "UbuntuHaskell" "Book 1"
.nf
.na
.SH NAME
example - man ページの一例。
.SH man ページとは？
Unix 系のオペレーティングシステムにおいては、普通、自然言語による電子的なマニュアルが内蔵されている。Unix 系オペレーティングシステムでは、歴史的にコマンドラインインタプリタが大いに活用されてきたが、そこにおいて様々な操作を文字列を通して指定するコマンドら、それぞれについて、マニュアルも区分けされている。そして、コマンドそれぞれのマニュアル (manual) は、man example などとすることで参照できる。この区分けされたマニュアル文書それぞれは、あるいはその集まり全体は、man ページと呼ばれる。
.P
ユーザが自ら man ページを作ることもできる。例えば、example.7 というファイルを作成してテキストエディタで編集し、nroff という形式に従って文章を書く。そして、man ~/example.7 などとすれば、man ページとしてその nroff 文章を開くことができる。man example などと開きたい場合、例えば bash において export MANPATH=~/man: として、~/man/man7 といったディレクトリに example.7 を配置すればよい。
.P
Unix 系オペレーティングシステムにおいて man ページは 1971 年頃から存在し、長い歴史を持っている。

